export const LOAD_COURSES_REQUEST = 'LOAD_COURSES_REQUEST';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_FAIL = 'LOAD_COURSES_FAIL';


export const LOAD_AUTHORS_REQUEST = 'LOAD_AUTHORS_REQUEST';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_AUTHORS_FAIL = 'LOAD_AUTHORS_FAIL';

